Implement user-supplied ignore list of modules (#18)
* Implement user-supplied ignore list of modules

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,7 +20,7 @@ jobs:
           ubuntu-version: 'latest'
           macos-version: 'latest'
           version: 0.1.7.1
-  tests:
+  builds:
     name: ${{ matrix.ghc }} on ${{ matrix.os }}
     needs: generate-matrix
     runs-on: ${{ matrix.os }}
@@ -122,14 +122,20 @@ jobs:
       - name: Build
         run: cabal build --project-file=cabal.static.project
 
-      - name: Test
-        run: cabal test --project-file=cabal.static.project all
-
       - name: Install
         run: |
           bin=$(cabal -v0 --project-file=cabal.static.project list-bin print-api)
           mkdir distribution
           cp ${bin} distribution/print-api
+
+      - name: Test
+        run: cabal test --project-file=cabal.static.project --test-options "--xml=../print-api/report.xml" all
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "report.xml"
 
       - name: File type
         run: file distribution/print-api
@@ -153,7 +159,7 @@ jobs:
   prerelease-head:
     name: Create a GitHub prerelease with the binary artifacts
     runs-on: ubuntu-latest
-    needs: ['tests', 'build-alpine']
+    needs: ['builds', 'build-alpine']
 
     steps:
     - uses: actions/download-artifact@v3
