Implement user-supplied ignore list of modules

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -62,6 +62,15 @@ jobs:
           mkdir distribution
           cp ${bin} distribution/print-api
 
+      - name: Test
+        run: cabal test --project-file=cabal.release.project --test-options "--xml=report.xml" all
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "report.xml"
+
       - name: File type
         run: file distribution/print-api
 
@@ -122,14 +131,20 @@ jobs:
       - name: Build
         run: cabal build --project-file=cabal.static.project
 
-      - name: Test
-        run: cabal test --project-file=cabal.static.project all
-
       - name: Install
         run: |
           bin=$(cabal -v0 --project-file=cabal.static.project list-bin print-api)
           mkdir distribution
           cp ${bin} distribution/print-api
+
+      - name: Test
+        run: cabal test --project-file=cabal.static.project --test-options "--xml=report.xml" all
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "report.xml"
 
       - name: File type
         run: file distribution/print-api
