Collect all test reports in a single workflow and print it in GitHub
closes #21

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -57,20 +57,23 @@ jobs:
         with:
           ghc-version: ${{ matrix.ghc }}
           cabal-version: 'latest'
+
       - name: Configure
         run: |
           ARCHITECTURE=$(uname -m)
           echo "ARCH=$ARCHITECTURE" >> $GITHUB_ENV
           echo ${{ env.ARCH }}
           cabal configure --enable-tests
+
       - name: Freeze
         run: cabal freeze --project-file=cabal.release.project
+
       - name: Cache
         uses: actions/cache@v4.0.2
         with:
           path: ${{ steps.setup-haskell.outputs.cabal-store }}
-          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('**/plan.json') }}
-          restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}-
+          key: ${{ matrix.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('**/plan.json') }}
+          restore-keys: ${{ matrix.os }}-ghc-${{ matrix.ghc }}-
 
       - name: Build
         run: cabal build --project-file=cabal.release.project
@@ -83,6 +86,17 @@ jobs:
             cp "${path}" distribution
           done
           echo "$GITHUB_WORKSPACE/distribution" >> "$GITHUB_PATH"
+          echo "REPORT_NAME=report-${{ matrix.os }}-ghc-${{ matrix.ghc }}" >> $GITHUB_ENV
+
+      - name: Test
+        run: cabal test --project-file=cabal.release.project --test-options "--xml=../print-api/${{ env.REPORT_NAME }}.xml" all
+
+      - name: Upload the test report
+        uses: actions/upload-artifact@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          name: ${{ env.REPORT_NAME }}
+          path: ${{ env.REPORT_NAME }}.xml
 
       - name: File type
         run: file distribution/*
@@ -100,14 +114,15 @@ jobs:
         run: |
           executables=( $(ls distribution) )
           version=$(./distribution/print-api --version)
-          archive="print-api-${version}-${{ runner.os }}-${{ env.ARCH }}-ghc-${{ matrix.ghc }}.tar.gz"
+          archive="print-api-${version}-${{ matrix.os }}-${{ env.ARCH }}-ghc-${{ matrix.ghc }}.tar.gz"
           tar -czvf "${archive}" -C distribution "${executables[@]}"
           echo "PRINTAPI_EXEC_TAR=${archive}" >> $GITHUB_ENV
+          echo "ARTIFACT_NAME=artifact-${{ matrix.os }}-ghc-${{ matrix.ghc }}" >> $GITHUB_ENV
 
       - name: Upload the executables archive
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
-          name: artifact
+          name: ${{ env.ARTIFACT_NAME }}
           path: ${{ env.PRINTAPI_EXEC_TAR }}
 
   build-alpine:
@@ -145,11 +160,12 @@ jobs:
       - name: Freeze
         run: cabal freeze --project-file=cabal.static.project
 
-      - uses: actions/cache@v4
+      - name: Cache
+        uses: actions/cache@v4
         with:
           path: ${{ steps.setup-haskell.outputs.cabal-store }}
-          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-${{ hashFiles('**/plan.json') }}
-          restore-keys: ${{ runner.os }}-${{ steps.setup.outputs.ghc-version }}-
+          key: alpine-ghc-${{ matrix.ghc }}-${{ hashFiles('**/plan.json') }}
+          restore-keys: alpine-3.20-${{ matrix.ghc }}-
 
       - name: Build
         run: cabal build --project-file=cabal.static.project
@@ -162,15 +178,17 @@ jobs:
             cp "${path}" distribution
           done
           echo "$GITHUB_WORKSPACE/distribution" >> "$GITHUB_PATH"
+          echo "REPORT_NAME=report-alpine-3.20-ghc-${{ matrix.ghc }}" >> $GITHUB_ENV
 
       - name: Test
-        run: cabal test --project-file=cabal.static.project --test-options "--xml=../print-api/report.xml" all
+        run: cabal test --project-file=cabal.static.project --test-options "--xml=../print-api/${REPORT_NAME}.xml" all
 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
+      - name: Upload the test report
+        uses: actions/upload-artifact@v4
         if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: "report.xml"
+        with: 
+          name: ${{ env.REPORT_NAME }}
+          path: ${{ env.REPORT_NAME }}.xml
 
       - name: File type
         run: file distribution/*
@@ -188,14 +206,15 @@ jobs:
         run: |
           executables=( $(ls distribution) )
           version=$(./distribution/print-api --version)
-          archive="print-api-${version}-${{ runner.os }}-${{ env.ARCH }}-static-ghc-${{ matrix.ghc }}.tar.gz"
+          archive="print-api-${version}-alpine-3.20-${{ env.ARCH }}-static-ghc-${{ matrix.ghc }}.tar.gz"
           tar -c -z -v -f "${archive}" -C distribution "${executables[@]}"
           echo "PRINTAPI_EXEC_TAR=${archive}" >> $GITHUB_ENV
+          echo "ARTIFACT_NAME=artifact-alpine-3.20-ghc-${{ matrix.ghc }}" >> $GITHUB_ENV
 
       - name: Upload the executables archive
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
-          name: artifact
+          name: ${{ env.ARTIFACT_NAME }}
           path: ${{ env.PRINTAPI_EXEC_TAR }}
 
   prerelease-head:
@@ -204,9 +223,10 @@ jobs:
     needs: ['builds', 'build-alpine']
 
     steps:
-    - uses: actions/download-artifact@v3
+    - uses: actions/download-artifact@v4
       with:
-        name: artifact
+        pattern: artifact-*
+        merge-multiple: true
         path: ./out
 
     - name: Release
