Put the newly-built print-api in the PATH of the CI runner (#19)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -36,6 +36,7 @@ jobs:
           cabal-file: print-api.cabal
           version: 0.1.7.1
           ubuntu-version: 'latest'
+
   tests:
     name: ${{ matrix.ghc }} on ${{ matrix.os }}
     needs: generate-matrix
@@ -77,6 +78,16 @@ jobs:
           bin=$(cabal -v0 --project-file=cabal.static.project list-bin print-api)
           mkdir distribution
           cp ${bin} distribution/print-api
+          echo "$GITHUB_WORKSPACE/distribution" >> "$GITHUB_PATH"
+
+      - name: Test
+        run: cabal test --project-file=cabal.static.project --test-options "--xml=../print-api/report.xml" all
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "report.xml"
 
       - name: File type
         run: file distribution/print-api
@@ -98,12 +109,12 @@ jobs:
           path: ${{ env.PRINTAPI_EXEC_TAR }}
 
   build-alpine:
-    name: ${{ matrix.ghc }} on alpine-3.19
+    name: ${{ matrix.ghc }} on alpine-3.20
     needs: generate-alpine-matrix
     runs-on: ${{ matrix.os }}
     strategy:
       matrix: ${{ fromJSON(needs.generate-alpine-matrix.outputs.matrix) }}
-    container: 'alpine:3.19'
+    container: 'alpine:3.20'
     steps:
       - name: Install extra dependencies
         shell: sh
@@ -141,14 +152,21 @@ jobs:
       - name: Build
         run: cabal build --project-file=cabal.static.project
 
-      - name: Test
-        run: cabal test --project-file=cabal.static.project all
-
       - name: Install
         run: |
           bin=$(cabal -v0 --project-file=cabal.static.project list-bin print-api)
           mkdir distribution
           cp ${bin} distribution/print-api
+          echo "$GITHUB_WORKSPACE/distribution" >> "$GITHUB_PATH"
+
+      - name: Test
+        run: cabal test --project-file=cabal.static.project --test-options "--xml=../print-api/report.xml" all
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "report.xml"
 
       - name: File type
         run: file distribution/print-api
